# Generated by transport/tools/fw_abi_gen.py. Do not edit.

import ctypes
import enum
import pathlib
import typing

_lib = ctypes.CDLL(str(pathlib.Path(__file__).parent / "build" / "librpc.so"))

RPC_MAX_FRAME = 512
RPC_HDR_LEN = 8
RPC_CRC_LEN = 2
RPC_MAX_PAYLOAD = 502
RPC_NS_MAX = 8
RPC_STATUS_TRANSPORT_BASE = 240
RPC_PROTOCOL_VERSION = 1
RPC_MAX_OPS = 32
RPC_RELAY_MAX_BYTES = 32
RPC_MAX_DEVICES = 4
RPC_NAME_MAX = 16
RPC_STR_MAX = 32
TMC2209_SYNC = 5
TMC2209_SYNC_MASK = 15
TMC2209_MASTER_ADDR = 255
TMC2209_WRITE_FLAG = 128
TMC2209_REG_MASK = 127
TMC2209_ADDR_MASK = 3
TMC2209_WRITE_LEN = 8
TMC2209_READ_REQ_LEN = 4
TMC2209_REPLY_LEN = 8
TMC2209_REG_COUNT = 23
TMC2209_OWNED_COUNT = 10
TMC2209_CONDITIONS_LATCHED = 7
TMC2209_CONDITIONS_FAULT = 54
TMC2209_LIB_IOIN_VERSION = 33
TMC2209_LINES_ALL = 15
TMC2209_STEP_MIN_PULSE_NS = 100
RPC_OK = 0
RPC_NO_METHOD = 240
RPC_BAD_FRAME = 241
RPC_INTERNAL = 242
RPC_ARG = 1
RPC_TX_TIMEOUT = 2
RPC_RX_TIMEOUT = 3
RPC_IO = 4
RPC_ECHO = 5
RPC_SYNC = 6
RPC_CRC = 7
RPC_REG = 8
RPC_NO_ACK = 9
RPC_ACCESS = 10
RPC_NO_BACKEND = 11
RPC_UNWIRED = 12
RPC_INVALID_SLOT = 13
RPC_MISMATCH = 14
RPC_BUSY = 15
RPC_IDLE = 16
RPC_RATE = 17
RPC_REFUSED = 18
RPC_STATUS_LAST = 19
TMC2209_ACCESS_READ = 1
TMC2209_ACCESS_WRITE = 2


class rpc_frame_t(enum.IntEnum):
    RPC_FRAME_REQ = 0
    RPC_FRAME_REP = 1
    RPC_FRAME_LOG = 2


RPC_FRAME_REQ = rpc_frame_t.RPC_FRAME_REQ
RPC_FRAME_REP = rpc_frame_t.RPC_FRAME_REP
RPC_FRAME_LOG = rpc_frame_t.RPC_FRAME_LOG


class rpc_ns_t(enum.IntEnum):
    RPC_NS_SYS = 0
    RPC_NS_RELAY = 1
    RPC_NS_RAW = 2
    RPC_NS_FILM = 3
    RPC_NS_COUNT = 4


RPC_NS_SYS = rpc_ns_t.RPC_NS_SYS
RPC_NS_RELAY = rpc_ns_t.RPC_NS_RELAY
RPC_NS_RAW = rpc_ns_t.RPC_NS_RAW
RPC_NS_FILM = rpc_ns_t.RPC_NS_FILM
RPC_NS_COUNT = rpc_ns_t.RPC_NS_COUNT


class rpc_sys_method_t(enum.IntEnum):
    RPC_SYS_VERSION = 0
    RPC_SYS_STATE = 1
    RPC_SYS_DEVICES = 2
    RPC_SYS_COUNT = 3


RPC_SYS_VERSION = rpc_sys_method_t.RPC_SYS_VERSION
RPC_SYS_STATE = rpc_sys_method_t.RPC_SYS_STATE
RPC_SYS_DEVICES = rpc_sys_method_t.RPC_SYS_DEVICES
RPC_SYS_COUNT = rpc_sys_method_t.RPC_SYS_COUNT


class rpc_relay_method_t(enum.IntEnum):
    RPC_RELAY_SEND = 0
    RPC_RELAY_COUNT = 1


RPC_RELAY_SEND = rpc_relay_method_t.RPC_RELAY_SEND
RPC_RELAY_COUNT = rpc_relay_method_t.RPC_RELAY_COUNT


class rpc_raw_method_t(enum.IntEnum):
    RPC_RAW_READ = 0
    RPC_RAW_POLL = 1
    RPC_RAW_WRITE = 2
    RPC_RAW_POLL_HEALTH = 3
    RPC_RAW_CLEAR_FAULTS = 4
    RPC_RAW_POLL_LOAD = 5
    RPC_RAW_POLL_PINS = 6
    RPC_RAW_POLL_VERSION = 7
    RPC_RAW_VERIFY_CONFIG = 8
    RPC_RAW_SET_VELOCITY = 9
    RPC_RAW_SET_CURRENT = 10
    RPC_RAW_BRINGUP = 11
    RPC_RAW_ALL_OWNED_VALID = 12
    RPC_RAW_INVALIDATE_OWNED = 13
    RPC_RAW_LINE_READ = 14
    RPC_RAW_LINE_WRITE = 15
    RPC_RAW_ENABLE = 16
    RPC_RAW_IS_ENABLED = 17
    RPC_RAW_MOVE = 18
    RPC_RAW_RETARGET = 19
    RPC_RAW_HALT = 20
    RPC_RAW_MOTION = 21
    RPC_RAW_COUNT = 22


RPC_RAW_READ = rpc_raw_method_t.RPC_RAW_READ
RPC_RAW_POLL = rpc_raw_method_t.RPC_RAW_POLL
RPC_RAW_WRITE = rpc_raw_method_t.RPC_RAW_WRITE
RPC_RAW_POLL_HEALTH = rpc_raw_method_t.RPC_RAW_POLL_HEALTH
RPC_RAW_CLEAR_FAULTS = rpc_raw_method_t.RPC_RAW_CLEAR_FAULTS
RPC_RAW_POLL_LOAD = rpc_raw_method_t.RPC_RAW_POLL_LOAD
RPC_RAW_POLL_PINS = rpc_raw_method_t.RPC_RAW_POLL_PINS
RPC_RAW_POLL_VERSION = rpc_raw_method_t.RPC_RAW_POLL_VERSION
RPC_RAW_VERIFY_CONFIG = rpc_raw_method_t.RPC_RAW_VERIFY_CONFIG
RPC_RAW_SET_VELOCITY = rpc_raw_method_t.RPC_RAW_SET_VELOCITY
RPC_RAW_SET_CURRENT = rpc_raw_method_t.RPC_RAW_SET_CURRENT
RPC_RAW_BRINGUP = rpc_raw_method_t.RPC_RAW_BRINGUP
RPC_RAW_ALL_OWNED_VALID = rpc_raw_method_t.RPC_RAW_ALL_OWNED_VALID
RPC_RAW_INVALIDATE_OWNED = rpc_raw_method_t.RPC_RAW_INVALIDATE_OWNED
RPC_RAW_LINE_READ = rpc_raw_method_t.RPC_RAW_LINE_READ
RPC_RAW_LINE_WRITE = rpc_raw_method_t.RPC_RAW_LINE_WRITE
RPC_RAW_ENABLE = rpc_raw_method_t.RPC_RAW_ENABLE
RPC_RAW_IS_ENABLED = rpc_raw_method_t.RPC_RAW_IS_ENABLED
RPC_RAW_MOVE = rpc_raw_method_t.RPC_RAW_MOVE
RPC_RAW_RETARGET = rpc_raw_method_t.RPC_RAW_RETARGET
RPC_RAW_HALT = rpc_raw_method_t.RPC_RAW_HALT
RPC_RAW_MOTION = rpc_raw_method_t.RPC_RAW_MOTION
RPC_RAW_COUNT = rpc_raw_method_t.RPC_RAW_COUNT


class rpc_mode_t(enum.IntEnum):
    RPC_MODE_IDLE = 0
    RPC_MODE_SCANNING = 1
    RPC_MODE_FAULT = 2


RPC_MODE_IDLE = rpc_mode_t.RPC_MODE_IDLE
RPC_MODE_SCANNING = rpc_mode_t.RPC_MODE_SCANNING
RPC_MODE_FAULT = rpc_mode_t.RPC_MODE_FAULT


class tmc2209_err_t(enum.IntEnum):
    TMC2209_OK = 0
    TMC2209_ERR_ARG = 1
    TMC2209_ERR_TX_TIMEOUT = 2
    TMC2209_ERR_RX_TIMEOUT = 3
    TMC2209_ERR_IO = 4
    TMC2209_ERR_ECHO = 5
    TMC2209_ERR_PREAMBLE = 6
    TMC2209_ERR_CRC = 7
    TMC2209_ERR_REG = 8
    TMC2209_ERR_NO_ACK = 9
    TMC2209_ERR_ACCESS = 10
    TMC2209_ERR_NO_BACKEND = 11
    TMC2209_ERR_UNWIRED = 12
    TMC2209_ERR_INVALID_SLOT = 13
    TMC2209_ERR_MISMATCH = 14
    TMC2209_ERR_BUSY = 15
    TMC2209_ERR_IDLE = 16
    TMC2209_ERR_RATE = 17


TMC2209_OK = tmc2209_err_t.TMC2209_OK
TMC2209_ERR_ARG = tmc2209_err_t.TMC2209_ERR_ARG
TMC2209_ERR_TX_TIMEOUT = tmc2209_err_t.TMC2209_ERR_TX_TIMEOUT
TMC2209_ERR_RX_TIMEOUT = tmc2209_err_t.TMC2209_ERR_RX_TIMEOUT
TMC2209_ERR_IO = tmc2209_err_t.TMC2209_ERR_IO
TMC2209_ERR_ECHO = tmc2209_err_t.TMC2209_ERR_ECHO
TMC2209_ERR_PREAMBLE = tmc2209_err_t.TMC2209_ERR_PREAMBLE
TMC2209_ERR_CRC = tmc2209_err_t.TMC2209_ERR_CRC
TMC2209_ERR_REG = tmc2209_err_t.TMC2209_ERR_REG
TMC2209_ERR_NO_ACK = tmc2209_err_t.TMC2209_ERR_NO_ACK
TMC2209_ERR_ACCESS = tmc2209_err_t.TMC2209_ERR_ACCESS
TMC2209_ERR_NO_BACKEND = tmc2209_err_t.TMC2209_ERR_NO_BACKEND
TMC2209_ERR_UNWIRED = tmc2209_err_t.TMC2209_ERR_UNWIRED
TMC2209_ERR_INVALID_SLOT = tmc2209_err_t.TMC2209_ERR_INVALID_SLOT
TMC2209_ERR_MISMATCH = tmc2209_err_t.TMC2209_ERR_MISMATCH
TMC2209_ERR_BUSY = tmc2209_err_t.TMC2209_ERR_BUSY
TMC2209_ERR_IDLE = tmc2209_err_t.TMC2209_ERR_IDLE
TMC2209_ERR_RATE = tmc2209_err_t.TMC2209_ERR_RATE


class tmc2209_reg_t(enum.IntEnum):
    TMC2209_GCONF = 0
    TMC2209_GSTAT = 1
    TMC2209_IFCNT = 2
    TMC2209_SLAVECONF = 3
    TMC2209_OTP_READ = 5
    TMC2209_IOIN = 6
    TMC2209_FACTORY_CONF = 7
    TMC2209_IHOLD_IRUN = 16
    TMC2209_TPOWERDOWN = 17
    TMC2209_TSTEP = 18
    TMC2209_TPWMTHRS = 19
    TMC2209_TCOOLTHRS = 20
    TMC2209_VACTUAL = 34
    TMC2209_SGTHRS = 64
    TMC2209_SG_RESULT = 65
    TMC2209_COOLCONF = 66
    TMC2209_MSCNT = 106
    TMC2209_MSCURACT = 107
    TMC2209_CHOPCONF = 108
    TMC2209_DRV_STATUS = 111
    TMC2209_PWMCONF = 112
    TMC2209_PWM_SCALE = 113
    TMC2209_PWM_AUTO = 114


TMC2209_GCONF = tmc2209_reg_t.TMC2209_GCONF
TMC2209_GSTAT = tmc2209_reg_t.TMC2209_GSTAT
TMC2209_IFCNT = tmc2209_reg_t.TMC2209_IFCNT
TMC2209_SLAVECONF = tmc2209_reg_t.TMC2209_SLAVECONF
TMC2209_OTP_READ = tmc2209_reg_t.TMC2209_OTP_READ
TMC2209_IOIN = tmc2209_reg_t.TMC2209_IOIN
TMC2209_FACTORY_CONF = tmc2209_reg_t.TMC2209_FACTORY_CONF
TMC2209_IHOLD_IRUN = tmc2209_reg_t.TMC2209_IHOLD_IRUN
TMC2209_TPOWERDOWN = tmc2209_reg_t.TMC2209_TPOWERDOWN
TMC2209_TSTEP = tmc2209_reg_t.TMC2209_TSTEP
TMC2209_TPWMTHRS = tmc2209_reg_t.TMC2209_TPWMTHRS
TMC2209_TCOOLTHRS = tmc2209_reg_t.TMC2209_TCOOLTHRS
TMC2209_VACTUAL = tmc2209_reg_t.TMC2209_VACTUAL
TMC2209_SGTHRS = tmc2209_reg_t.TMC2209_SGTHRS
TMC2209_SG_RESULT = tmc2209_reg_t.TMC2209_SG_RESULT
TMC2209_COOLCONF = tmc2209_reg_t.TMC2209_COOLCONF
TMC2209_MSCNT = tmc2209_reg_t.TMC2209_MSCNT
TMC2209_MSCURACT = tmc2209_reg_t.TMC2209_MSCURACT
TMC2209_CHOPCONF = tmc2209_reg_t.TMC2209_CHOPCONF
TMC2209_DRV_STATUS = tmc2209_reg_t.TMC2209_DRV_STATUS
TMC2209_PWMCONF = tmc2209_reg_t.TMC2209_PWMCONF
TMC2209_PWM_SCALE = tmc2209_reg_t.TMC2209_PWM_SCALE
TMC2209_PWM_AUTO = tmc2209_reg_t.TMC2209_PWM_AUTO


class tmc2209_class_t(enum.IntEnum):
    TMC2209_CLASS_UNKNOWN = 0
    TMC2209_CLASS_VOLATILE = 1
    TMC2209_CLASS_OWNED = 2
    TMC2209_CLASS_CONSTANT = 3


TMC2209_CLASS_UNKNOWN = tmc2209_class_t.TMC2209_CLASS_UNKNOWN
TMC2209_CLASS_VOLATILE = tmc2209_class_t.TMC2209_CLASS_VOLATILE
TMC2209_CLASS_OWNED = tmc2209_class_t.TMC2209_CLASS_OWNED
TMC2209_CLASS_CONSTANT = tmc2209_class_t.TMC2209_CLASS_CONSTANT


class tmc2209_condition_t(enum.IntEnum):
    TMC2209_DRIVER_RESET = 1
    TMC2209_DRIVER_FAULT = 2
    TMC2209_UNDERVOLTAGE = 4
    TMC2209_OVERTEMP_WARNING = 8
    TMC2209_OVERTEMP_SHUTDOWN = 16
    TMC2209_SHORT_CIRCUIT = 32
    TMC2209_OPEN_LOAD = 64
    TMC2209_STANDSTILL = 128


TMC2209_DRIVER_RESET = tmc2209_condition_t.TMC2209_DRIVER_RESET
TMC2209_DRIVER_FAULT = tmc2209_condition_t.TMC2209_DRIVER_FAULT
TMC2209_UNDERVOLTAGE = tmc2209_condition_t.TMC2209_UNDERVOLTAGE
TMC2209_OVERTEMP_WARNING = tmc2209_condition_t.TMC2209_OVERTEMP_WARNING
TMC2209_OVERTEMP_SHUTDOWN = tmc2209_condition_t.TMC2209_OVERTEMP_SHUTDOWN
TMC2209_SHORT_CIRCUIT = tmc2209_condition_t.TMC2209_SHORT_CIRCUIT
TMC2209_OPEN_LOAD = tmc2209_condition_t.TMC2209_OPEN_LOAD
TMC2209_STANDSTILL = tmc2209_condition_t.TMC2209_STANDSTILL


class tmc2209_mres_t(enum.IntEnum):
    TMC2209_MRES_256 = 0
    TMC2209_MRES_128 = 1
    TMC2209_MRES_64 = 2
    TMC2209_MRES_32 = 3
    TMC2209_MRES_16 = 4
    TMC2209_MRES_8 = 5
    TMC2209_MRES_4 = 6
    TMC2209_MRES_2 = 7
    TMC2209_MRES_FULL = 8


TMC2209_MRES_256 = tmc2209_mres_t.TMC2209_MRES_256
TMC2209_MRES_128 = tmc2209_mres_t.TMC2209_MRES_128
TMC2209_MRES_64 = tmc2209_mres_t.TMC2209_MRES_64
TMC2209_MRES_32 = tmc2209_mres_t.TMC2209_MRES_32
TMC2209_MRES_16 = tmc2209_mres_t.TMC2209_MRES_16
TMC2209_MRES_8 = tmc2209_mres_t.TMC2209_MRES_8
TMC2209_MRES_4 = tmc2209_mres_t.TMC2209_MRES_4
TMC2209_MRES_2 = tmc2209_mres_t.TMC2209_MRES_2
TMC2209_MRES_FULL = tmc2209_mres_t.TMC2209_MRES_FULL


class tmc2209_tbl_t(enum.IntEnum):
    TMC2209_TBL_16 = 0
    TMC2209_TBL_24 = 1
    TMC2209_TBL_32 = 2
    TMC2209_TBL_40 = 3


TMC2209_TBL_16 = tmc2209_tbl_t.TMC2209_TBL_16
TMC2209_TBL_24 = tmc2209_tbl_t.TMC2209_TBL_24
TMC2209_TBL_32 = tmc2209_tbl_t.TMC2209_TBL_32
TMC2209_TBL_40 = tmc2209_tbl_t.TMC2209_TBL_40


class tmc2209_seup_t(enum.IntEnum):
    TMC2209_SEUP_1 = 0
    TMC2209_SEUP_2 = 1
    TMC2209_SEUP_4 = 2
    TMC2209_SEUP_8 = 3


TMC2209_SEUP_1 = tmc2209_seup_t.TMC2209_SEUP_1
TMC2209_SEUP_2 = tmc2209_seup_t.TMC2209_SEUP_2
TMC2209_SEUP_4 = tmc2209_seup_t.TMC2209_SEUP_4
TMC2209_SEUP_8 = tmc2209_seup_t.TMC2209_SEUP_8


class tmc2209_sedn_t(enum.IntEnum):
    TMC2209_SEDN_32 = 0
    TMC2209_SEDN_8 = 1
    TMC2209_SEDN_2 = 2
    TMC2209_SEDN_1 = 3


TMC2209_SEDN_32 = tmc2209_sedn_t.TMC2209_SEDN_32
TMC2209_SEDN_8 = tmc2209_sedn_t.TMC2209_SEDN_8
TMC2209_SEDN_2 = tmc2209_sedn_t.TMC2209_SEDN_2
TMC2209_SEDN_1 = tmc2209_sedn_t.TMC2209_SEDN_1


class tmc2209_line_t(enum.IntEnum):
    TMC2209_LINE_ENN = 0
    TMC2209_LINE_DIR = 1
    TMC2209_LINE_STEP = 2
    TMC2209_LINE_DIAG = 3
    TMC2209_LINE_COUNT = 4


TMC2209_LINE_ENN = tmc2209_line_t.TMC2209_LINE_ENN
TMC2209_LINE_DIR = tmc2209_line_t.TMC2209_LINE_DIR
TMC2209_LINE_STEP = tmc2209_line_t.TMC2209_LINE_STEP
TMC2209_LINE_DIAG = tmc2209_line_t.TMC2209_LINE_DIAG
TMC2209_LINE_COUNT = tmc2209_line_t.TMC2209_LINE_COUNT


class rpc_req_hdr_t(ctypes.Structure):
    _fields_ = [
        ("type", ctypes.c_uint8),
        ("ns", ctypes.c_uint8),
        ("method", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
        ("id", ctypes.c_uint16),
        ("_pad2", ctypes.c_uint16),
    ]


class rpc_rep_hdr_t(ctypes.Structure):
    _fields_ = [
        ("type", ctypes.c_uint8),
        ("status", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 2),
        ("id", ctypes.c_uint16),
        ("_pad2", ctypes.c_uint16),
    ]


class rpc_log_hdr_t(ctypes.Structure):
    _fields_ = [
        ("type", ctypes.c_uint8),
        ("level", ctypes.c_uint8),
        ("_pad", ctypes.c_uint16),
        ("uptime_ms", ctypes.c_uint32),
    ]


class rpc_buf_t(ctypes.Union):
    _fields_ = [
        ("req", rpc_req_hdr_t),
        ("rep", rpc_rep_hdr_t),
        ("log", rpc_log_hdr_t),
        ("bytes", ctypes.c_uint8 * 512),
    ]


class rpc_view_t(ctypes.Structure):
    _fields_ = [
        ("type", ctypes.c_uint8),
        ("hdr", ctypes.c_void_p),
        ("payload", ctypes.c_void_p),
        ("payload_len", ctypes.c_size_t),
    ]


class rpc_dev_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_op_t(ctypes.Structure):
    _fields_ = [
        ("value", ctypes.c_uint32),
        ("reg", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_sys_version_ret(ctypes.Structure):
    _fields_ = [
        ("protocol", ctypes.c_uint16),
        ("reset_reason", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
        ("project", ctypes.c_char * 32),
        ("version", ctypes.c_char * 32),
        ("idf", ctypes.c_char * 32),
    ]


class rpc_sys_state_ret(ctypes.Structure):
    _fields_ = [
        ("uptime_ms", ctypes.c_uint32),
        ("device_count", ctypes.c_uint16),
        ("mode", ctypes.c_uint8),
        ("ready", ctypes.c_uint8),
    ]


class rpc_dev_info_t(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char * 16),
        ("addr", ctypes.c_uint8),
        ("wired", ctypes.c_uint8),
        ("has_uart", ctypes.c_uint8),
        ("has_stepgen", ctypes.c_uint8),
    ]


class rpc_sys_devices_ret(ctypes.Structure):
    _fields_ = [
        ("count", ctypes.c_uint32),
    ]


class rpc_relay_send_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("reply_len", ctypes.c_uint8),
        ("count", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
    ]


class rpc_relay_send_ret(ctypes.Structure):
    _fields_ = [
        ("outcome", ctypes.c_uint8),
        ("count", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 2),
        ("rx", ctypes.c_uint8 * 32),
    ]


class rpc_raw_read_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("reg", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 2),
    ]


class rpc_raw_read_ret(ctypes.Structure):
    _fields_ = [
        ("value", ctypes.c_uint32),
    ]


class rpc_raw_write_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
        ("count", ctypes.c_uint32),
    ]


class rpc_raw_write_ret(ctypes.Structure):
    _fields_ = [
        ("failed_at", ctypes.c_uint16),
        ("_pad", ctypes.c_uint16),
    ]


class rpc_raw_poll_health_ret(ctypes.Structure):
    _fields_ = [
        ("conditions", ctypes.c_uint32),
    ]


class rpc_raw_clear_faults_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
        ("conditions", ctypes.c_uint32),
    ]


class rpc_raw_poll_load_ret(ctypes.Structure):
    _fields_ = [
        ("value", ctypes.c_uint16),
        ("usable", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
    ]


class rpc_raw_poll_pins_ret(ctypes.Structure):
    _fields_ = [
        ("value", ctypes.c_uint32),
    ]


class rpc_raw_poll_version_ret(ctypes.Structure):
    _fields_ = [
        ("version", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_raw_verify_config_ret(ctypes.Structure):
    _fields_ = [
        ("mismatched", ctypes.c_uint32),
        ("agrees", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_raw_set_velocity_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
        ("velocity", ctypes.c_int32),
    ]


class rpc_raw_set_current_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("ihold", ctypes.c_uint8),
        ("irun", ctypes.c_uint8),
        ("iholddelay", ctypes.c_uint8),
    ]


class rpc_raw_bringup_ret(ctypes.Structure):
    _fields_ = [
        ("gstat_at_bringup", ctypes.c_uint32),
    ]


class rpc_raw_all_owned_valid_ret(ctypes.Structure):
    _fields_ = [
        ("valid", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_raw_line_read_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("line", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 2),
    ]


class rpc_raw_line_read_ret(ctypes.Structure):
    _fields_ = [
        ("level", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_raw_line_write_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("line", ctypes.c_uint8),
        ("level", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
    ]


class rpc_raw_enable_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("on", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 2),
    ]


class rpc_raw_is_enabled_ret(ctypes.Structure):
    _fields_ = [
        ("on", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
    ]


class rpc_raw_move_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("dir", ctypes.c_uint8),
        ("shaft", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
        ("pulses", ctypes.c_uint32),
        ("pullin_pps", ctypes.c_uint32),
        ("cruise_pps", ctypes.c_uint32),
        ("accel_pps_s", ctypes.c_uint32),
    ]


class rpc_raw_retarget_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 3),
        ("cruise_pps", ctypes.c_uint32),
    ]


class rpc_raw_halt_args(ctypes.Structure):
    _fields_ = [
        ("idx", ctypes.c_uint8),
        ("immediate", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8 * 2),
    ]


class rpc_raw_motion_ret(ctypes.Structure):
    _fields_ = [
        ("emitted", ctypes.c_uint32),
        ("rate_pps", ctypes.c_uint32),
        ("running", ctypes.c_uint8),
        ("dir", ctypes.c_uint8),
        ("shaft", ctypes.c_uint8),
        ("_pad", ctypes.c_uint8),
    ]


class tmc2209_load_t(ctypes.Structure):
    _fields_ = [
        ("value", ctypes.c_uint16),
        ("usable", ctypes.c_bool),
    ]


class tmc2209_gconf_t(ctypes.Structure):
    _fields_ = [
        ("i_scale_analog", ctypes.c_bool),
        ("internal_rsense", ctypes.c_bool),
        ("en_spreadcycle", ctypes.c_bool),
        ("shaft", ctypes.c_bool),
        ("index_otpw", ctypes.c_bool),
        ("index_step", ctypes.c_bool),
        ("pdn_disable", ctypes.c_bool),
        ("mstep_reg_select", ctypes.c_bool),
        ("multistep_filt", ctypes.c_bool),
        ("test_mode", ctypes.c_bool),
    ]


class tmc2209_chopconf_t(ctypes.Structure):
    _fields_ = [
        ("toff", ctypes.c_uint8),
        ("hstrt", ctypes.c_uint8),
        ("hend", ctypes.c_uint8),
        ("tbl", ctypes.c_uint),
        ("vsense", ctypes.c_bool),
        ("mres", ctypes.c_uint),
        ("intpol", ctypes.c_bool),
        ("dedge", ctypes.c_bool),
        ("diss2g", ctypes.c_bool),
        ("diss2vs", ctypes.c_bool),
    ]


class tmc2209_ihold_irun_t(ctypes.Structure):
    _fields_ = [
        ("ihold", ctypes.c_uint8),
        ("irun", ctypes.c_uint8),
        ("iholddelay", ctypes.c_uint8),
    ]


class tmc2209_coolconf_t(ctypes.Structure):
    _fields_ = [
        ("semin", ctypes.c_uint8),
        ("seup", ctypes.c_uint),
        ("semax", ctypes.c_uint8),
        ("sedn", ctypes.c_uint),
        ("seimin", ctypes.c_bool),
    ]


class tmc2209_drv_status_t(ctypes.Structure):
    _fields_ = [
        ("otpw", ctypes.c_bool),
        ("ot", ctypes.c_bool),
        ("s2ga", ctypes.c_bool),
        ("s2gb", ctypes.c_bool),
        ("s2vsa", ctypes.c_bool),
        ("s2vsb", ctypes.c_bool),
        ("ola", ctypes.c_bool),
        ("olb", ctypes.c_bool),
        ("t120", ctypes.c_bool),
        ("t143", ctypes.c_bool),
        ("t150", ctypes.c_bool),
        ("t157", ctypes.c_bool),
        ("cs_actual", ctypes.c_uint8),
        ("stealth", ctypes.c_bool),
        ("stst", ctypes.c_bool),
    ]


class tmc2209_gstat_t(ctypes.Structure):
    _fields_ = [
        ("reset", ctypes.c_bool),
        ("drv_err", ctypes.c_bool),
        ("uv_cp", ctypes.c_bool),
    ]


class tmc2209_ioin_t(ctypes.Structure):
    _fields_ = [
        ("enn", ctypes.c_bool),
        ("ms1", ctypes.c_bool),
        ("ms2", ctypes.c_bool),
        ("diag", ctypes.c_bool),
        ("pdn_uart", ctypes.c_bool),
        ("step", ctypes.c_bool),
        ("spread_en", ctypes.c_bool),
        ("dir", ctypes.c_bool),
        ("version", ctypes.c_uint8),
    ]


class tmc2209_mscuract_t(ctypes.Structure):
    _fields_ = [
        ("cur_a", ctypes.c_int16),
        ("cur_b", ctypes.c_int16),
    ]


class tmc2209_pwm_scale_t(ctypes.Structure):
    _fields_ = [
        ("sum", ctypes.c_uint8),
        ("automatic", ctypes.c_int16),
    ]


class tmc2209_pwm_auto_t(ctypes.Structure):
    _fields_ = [
        ("ofs_auto", ctypes.c_uint8),
        ("grad_auto", ctypes.c_uint8),
    ]


rpc_status_t = ctypes.c_uint8
rpc_raw_poll_args = rpc_raw_read_args
rpc_raw_poll_ret = rpc_raw_read_ret
rpc_raw_poll_health_args = rpc_dev_args
rpc_raw_poll_load_args = rpc_dev_args
rpc_raw_poll_pins_args = rpc_dev_args
rpc_raw_poll_version_args = rpc_dev_args
rpc_raw_verify_config_args = rpc_dev_args
rpc_raw_bringup_args = rpc_raw_write_args
rpc_raw_all_owned_valid_args = rpc_dev_args
rpc_raw_invalidate_owned_args = rpc_dev_args
rpc_raw_is_enabled_args = rpc_dev_args
rpc_raw_motion_args = rpc_dev_args

SIZEOF = {
    "rpc_req_hdr_t": 8,
    "rpc_rep_hdr_t": 8,
    "rpc_log_hdr_t": 8,
    "rpc_buf_t": 512,
    "rpc_view_t": 32,
    "rpc_dev_args": 4,
    "rpc_op_t": 8,
    "rpc_sys_version_ret": 100,
    "rpc_sys_state_ret": 8,
    "rpc_dev_info_t": 20,
    "rpc_sys_devices_ret": 4,
    "rpc_relay_send_args": 4,
    "rpc_relay_send_ret": 36,
    "rpc_raw_read_args": 4,
    "rpc_raw_read_ret": 4,
    "rpc_raw_write_args": 8,
    "rpc_raw_write_ret": 4,
    "rpc_raw_poll_health_ret": 4,
    "rpc_raw_clear_faults_args": 8,
    "rpc_raw_poll_load_ret": 4,
    "rpc_raw_poll_pins_ret": 4,
    "rpc_raw_poll_version_ret": 4,
    "rpc_raw_verify_config_ret": 8,
    "rpc_raw_set_velocity_args": 8,
    "rpc_raw_set_current_args": 4,
    "rpc_raw_bringup_ret": 4,
    "rpc_raw_all_owned_valid_ret": 4,
    "rpc_raw_line_read_args": 4,
    "rpc_raw_line_read_ret": 4,
    "rpc_raw_line_write_args": 4,
    "rpc_raw_enable_args": 4,
    "rpc_raw_is_enabled_ret": 4,
    "rpc_raw_move_args": 20,
    "rpc_raw_retarget_args": 8,
    "rpc_raw_halt_args": 4,
    "rpc_raw_motion_ret": 12,
    "tmc2209_load_t": 4,
    "tmc2209_gconf_t": 10,
    "tmc2209_chopconf_t": 20,
    "tmc2209_ihold_irun_t": 3,
    "tmc2209_coolconf_t": 20,
    "tmc2209_drv_status_t": 15,
    "tmc2209_gstat_t": 3,
    "tmc2209_ioin_t": 9,
    "tmc2209_mscuract_t": 4,
    "tmc2209_pwm_scale_t": 4,
    "tmc2209_pwm_auto_t": 2,
}


class Flex(typing.NamedTuple):
    field: str
    count_field: str
    elem: type


FLEX = {
    rpc_sys_devices_ret: Flex("devs", "count", rpc_dev_info_t),
    rpc_relay_send_args: Flex("tx", "count", ctypes.c_uint8),
    rpc_raw_write_args: Flex("ops", "count", rpc_op_t),
}


class RpcError(Exception):
    def __init__(self, status):
        self.status = status
        super().__init__(f"{rpc_strerror(status).decode()} ({status})")


class RpcNoMethod(RpcError):
    pass


class RpcBadFrame(RpcError):
    pass


class RpcInternal(RpcError):
    pass


class RpcArg(RpcError):
    pass


class RpcTxTimeout(RpcError):
    pass


class RpcRxTimeout(RpcError):
    pass


class RpcIo(RpcError):
    pass


class RpcEcho(RpcError):
    pass


class RpcSync(RpcError):
    pass


class RpcCrc(RpcError):
    pass


class RpcReg(RpcError):
    pass


class RpcNoAck(RpcError):
    pass


class RpcAccess(RpcError):
    pass


class RpcNoBackend(RpcError):
    pass


class RpcUnwired(RpcError):
    pass


class RpcInvalidSlot(RpcError):
    pass


class RpcMismatch(RpcError):
    pass


class RpcBusy(RpcError):
    pass


class RpcIdle(RpcError):
    pass


class RpcRate(RpcError):
    pass


class RpcRefused(RpcError):
    pass


STATUS_EXCEPTION = {
    RPC_NO_METHOD: RpcNoMethod,
    RPC_BAD_FRAME: RpcBadFrame,
    RPC_INTERNAL: RpcInternal,
    RPC_ARG: RpcArg,
    RPC_TX_TIMEOUT: RpcTxTimeout,
    RPC_RX_TIMEOUT: RpcRxTimeout,
    RPC_IO: RpcIo,
    RPC_ECHO: RpcEcho,
    RPC_SYNC: RpcSync,
    RPC_CRC: RpcCrc,
    RPC_REG: RpcReg,
    RPC_NO_ACK: RpcNoAck,
    RPC_ACCESS: RpcAccess,
    RPC_NO_BACKEND: RpcNoBackend,
    RPC_UNWIRED: RpcUnwired,
    RPC_INVALID_SLOT: RpcInvalidSlot,
    RPC_MISMATCH: RpcMismatch,
    RPC_BUSY: RpcBusy,
    RPC_IDLE: RpcIdle,
    RPC_RATE: RpcRate,
    RPC_REFUSED: RpcRefused,
}


def raise_for_status(status):
    if status != RPC_OK:
        raise STATUS_EXCEPTION.get(status, RpcError)(status)


rpc_frame_seal_req = _lib.rpc_frame_seal_req
rpc_frame_seal_req.restype = ctypes.c_size_t
rpc_frame_seal_req.argtypes = [
    ctypes.POINTER(rpc_buf_t),
    ctypes.c_uint16,
    ctypes.c_uint8,
    ctypes.c_uint8,
    ctypes.c_size_t,
]

rpc_frame_seal_rep = _lib.rpc_frame_seal_rep
rpc_frame_seal_rep.restype = ctypes.c_size_t
rpc_frame_seal_rep.argtypes = [
    ctypes.POINTER(rpc_buf_t),
    ctypes.c_uint16,
    ctypes.c_ubyte,
    ctypes.c_size_t,
]

rpc_frame_seal_log = _lib.rpc_frame_seal_log
rpc_frame_seal_log.restype = ctypes.c_size_t
rpc_frame_seal_log.argtypes = [
    ctypes.POINTER(rpc_buf_t),
    ctypes.c_uint8,
    ctypes.c_uint32,
    ctypes.c_size_t,
]

rpc_frame_open = _lib.rpc_frame_open
rpc_frame_open.restype = ctypes.c_bool
rpc_frame_open.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.POINTER(rpc_view_t)]

cobs_encode = _lib.cobs_encode
cobs_encode.restype = ctypes.c_size_t
cobs_encode.argtypes = [
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_size_t,
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_size_t,
]

cobs_decode = _lib.cobs_decode
cobs_decode.restype = ctypes.c_size_t
cobs_decode.argtypes = [
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_size_t,
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_size_t,
]

crc16_ccitt = _lib.crc16_ccitt
crc16_ccitt.restype = ctypes.c_uint16
crc16_ccitt.argtypes = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t]

rpc_strerror = _lib.rpc_strerror
rpc_strerror.restype = ctypes.c_char_p
rpc_strerror.argtypes = [ctypes.c_ubyte]

tmc2209_strerror = _lib.tmc2209_strerror
tmc2209_strerror.restype = ctypes.c_char_p
tmc2209_strerror.argtypes = [ctypes.c_uint]

tmc2209_crc8 = _lib.tmc2209_crc8
tmc2209_crc8.restype = ctypes.c_uint8
tmc2209_crc8.argtypes = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t]

tmc2209_frame_write = _lib.tmc2209_frame_write
tmc2209_frame_write.restype = None
tmc2209_frame_write.argtypes = [
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_uint8,
    ctypes.c_uint8,
    ctypes.c_uint32,
]

tmc2209_frame_read_request = _lib.tmc2209_frame_read_request
tmc2209_frame_read_request.restype = None
tmc2209_frame_read_request.argtypes = [
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_uint8,
    ctypes.c_uint8,
]

tmc2209_frame_parse_reply = _lib.tmc2209_frame_parse_reply
tmc2209_frame_parse_reply.restype = ctypes.c_uint
tmc2209_frame_parse_reply.argtypes = [
    ctypes.POINTER(ctypes.c_uint8),
    ctypes.c_uint8,
    ctypes.POINTER(ctypes.c_uint32),
]

tmc2209_reg_slot = _lib.tmc2209_reg_slot
tmc2209_reg_slot.restype = ctypes.c_int
tmc2209_reg_slot.argtypes = [ctypes.c_uint]

tmc2209_reg_access = _lib.tmc2209_reg_access
tmc2209_reg_access.restype = ctypes.c_uint8
tmc2209_reg_access.argtypes = [ctypes.c_uint]

tmc2209_reg_class = _lib.tmc2209_reg_class
tmc2209_reg_class.restype = ctypes.c_uint
tmc2209_reg_class.argtypes = [ctypes.c_uint]

tmc2209_reg_name = _lib.tmc2209_reg_name
tmc2209_reg_name.restype = ctypes.c_char_p
tmc2209_reg_name.argtypes = [ctypes.c_uint]

tmc2209_reg_at = _lib.tmc2209_reg_at
tmc2209_reg_at.restype = ctypes.c_uint
tmc2209_reg_at.argtypes = [ctypes.c_int]

tmc2209_reg_access_at = _lib.tmc2209_reg_access_at
tmc2209_reg_access_at.restype = ctypes.c_uint8
tmc2209_reg_access_at.argtypes = [ctypes.c_int]

tmc2209_reg_class_at = _lib.tmc2209_reg_class_at
tmc2209_reg_class_at.restype = ctypes.c_uint
tmc2209_reg_class_at.argtypes = [ctypes.c_int]

tmc2209_mres_microsteps = _lib.tmc2209_mres_microsteps
tmc2209_mres_microsteps.restype = ctypes.c_uint16
tmc2209_mres_microsteps.argtypes = [ctypes.c_uint]

tmc2209_gconf_encode = _lib.tmc2209_gconf_encode
tmc2209_gconf_encode.restype = ctypes.c_uint32
tmc2209_gconf_encode.argtypes = [ctypes.POINTER(tmc2209_gconf_t)]

tmc2209_gconf_decode = _lib.tmc2209_gconf_decode
tmc2209_gconf_decode.restype = tmc2209_gconf_t
tmc2209_gconf_decode.argtypes = [ctypes.c_uint32]

tmc2209_chopconf_encode = _lib.tmc2209_chopconf_encode
tmc2209_chopconf_encode.restype = ctypes.c_uint32
tmc2209_chopconf_encode.argtypes = [ctypes.POINTER(tmc2209_chopconf_t)]

tmc2209_chopconf_decode = _lib.tmc2209_chopconf_decode
tmc2209_chopconf_decode.restype = tmc2209_chopconf_t
tmc2209_chopconf_decode.argtypes = [ctypes.c_uint32]

tmc2209_ihold_irun_encode = _lib.tmc2209_ihold_irun_encode
tmc2209_ihold_irun_encode.restype = ctypes.c_uint32
tmc2209_ihold_irun_encode.argtypes = [ctypes.POINTER(tmc2209_ihold_irun_t)]

tmc2209_ihold_irun_decode = _lib.tmc2209_ihold_irun_decode
tmc2209_ihold_irun_decode.restype = tmc2209_ihold_irun_t
tmc2209_ihold_irun_decode.argtypes = [ctypes.c_uint32]

tmc2209_coolconf_encode = _lib.tmc2209_coolconf_encode
tmc2209_coolconf_encode.restype = ctypes.c_uint32
tmc2209_coolconf_encode.argtypes = [ctypes.POINTER(tmc2209_coolconf_t)]

tmc2209_coolconf_decode = _lib.tmc2209_coolconf_decode
tmc2209_coolconf_decode.restype = tmc2209_coolconf_t
tmc2209_coolconf_decode.argtypes = [ctypes.c_uint32]

tmc2209_drv_status_decode = _lib.tmc2209_drv_status_decode
tmc2209_drv_status_decode.restype = tmc2209_drv_status_t
tmc2209_drv_status_decode.argtypes = [ctypes.c_uint32]

tmc2209_gstat_encode = _lib.tmc2209_gstat_encode
tmc2209_gstat_encode.restype = ctypes.c_uint32
tmc2209_gstat_encode.argtypes = [ctypes.POINTER(tmc2209_gstat_t)]

tmc2209_gstat_decode = _lib.tmc2209_gstat_decode
tmc2209_gstat_decode.restype = tmc2209_gstat_t
tmc2209_gstat_decode.argtypes = [ctypes.c_uint32]

tmc2209_ifcnt_decode = _lib.tmc2209_ifcnt_decode
tmc2209_ifcnt_decode.restype = ctypes.c_uint8
tmc2209_ifcnt_decode.argtypes = [ctypes.c_uint32]

tmc2209_ioin_decode = _lib.tmc2209_ioin_decode
tmc2209_ioin_decode.restype = tmc2209_ioin_t
tmc2209_ioin_decode.argtypes = [ctypes.c_uint32]

tmc2209_vactual_decode = _lib.tmc2209_vactual_decode
tmc2209_vactual_decode.restype = ctypes.c_int32
tmc2209_vactual_decode.argtypes = [ctypes.c_uint32]

tmc2209_vactual_encode = _lib.tmc2209_vactual_encode
tmc2209_vactual_encode.restype = ctypes.c_uint32
tmc2209_vactual_encode.argtypes = [ctypes.c_int32]

tmc2209_mscuract_decode = _lib.tmc2209_mscuract_decode
tmc2209_mscuract_decode.restype = tmc2209_mscuract_t
tmc2209_mscuract_decode.argtypes = [ctypes.c_uint32]

tmc2209_pwm_scale_decode = _lib.tmc2209_pwm_scale_decode
tmc2209_pwm_scale_decode.restype = tmc2209_pwm_scale_t
tmc2209_pwm_scale_decode.argtypes = [ctypes.c_uint32]

tmc2209_pwm_auto_decode = _lib.tmc2209_pwm_auto_decode
tmc2209_pwm_auto_decode.restype = tmc2209_pwm_auto_t
tmc2209_pwm_auto_decode.argtypes = [ctypes.c_uint32]
