"""Client for Canon's Camera Control API (CCAPI)."""

from portable.ccapi.camera import Camera
from portable.ccapi.config import (
    DEFAULT_PORT,
    DEFAULT_SSL_PORT,
    CameraConfig,
    Credentials,
)
from portable.ccapi.endpoints import (
    STREAMED,
    Endpoint,
    Methods,
    Registry,
    Resource,
    Volatility,
    volatility_of,
)
from portable.ccapi.errors import (
    AuthenticationError,
    CcapiError,
    DeviceBusyError,
    DeviceError,
    FeatureMissingError,
    ForbiddenError,
    InvalidRequestError,
    InvalidStateError,
    LinkError,
    MethodNotAllowedError,
    NotActivatedError,
    NotConnectedError,
    ProtocolError,
    RangeError,
    ShootingError,
    StorageError,
    UnacceptableVersionError,
    UnreachableError,
    error_for,
    worth_retrying,
)
from portable.ccapi.events import Events, Feed
from portable.ccapi.filesystem import Filesystem
from portable.ccapi.framing import Unpacker, pack, unpack
from portable.ccapi.functions import Functions
from portable.ccapi.link import HttpTransport, Link, RawReply, Transport
from portable.ccapi.live_view import CameraDisplay, LiveView, Stream, ViewSize
from portable.ccapi.movie import Movie
from portable.ccapi.settings import Setting, Settings
from portable.ccapi.shooting import (
    FlickerResult,
    FocusStep,
    HeldButton,
    Shooting,
    ShutterAction,
    ZoomAction,
)
from portable.ccapi.status import Status
from portable.ccapi.vocabulary import (
    Access,
    BatteryInfo,
    CameraState,
    ContentKind,
    DeviceInfo,
    ErrorBody,
    FileInfo,
    FileType,
    ImageQuality,
    LensInfo,
    LinkState,
    Packet,
    PacketKind,
    PollWait,
    PowerSource,
    PowerState,
    SettingValue,
    StateChange,
    Storage,
    ThermalRestriction,
)

__all__ = [
    "DEFAULT_PORT",
    "DEFAULT_SSL_PORT",
    "STREAMED",
    "Access",
    "AuthenticationError",
    "BatteryInfo",
    "Camera",
    "CameraConfig",
    "CameraDisplay",
    "CameraState",
    "CcapiError",
    "ContentKind",
    "Credentials",
    "DeviceBusyError",
    "DeviceError",
    "DeviceInfo",
    "Endpoint",
    "ErrorBody",
    "Events",
    "FeatureMissingError",
    "Feed",
    "FileInfo",
    "FileType",
    "Filesystem",
    "FlickerResult",
    "FocusStep",
    "ForbiddenError",
    "Functions",
    "ImageQuality",
    "HeldButton",
    "HttpTransport",
    "InvalidRequestError",
    "InvalidStateError",
    "LensInfo",
    "Link",
    "LinkError",
    "LinkState",
    "LiveView",
    "MethodNotAllowedError",
    "Methods",
    "Movie",
    "NotActivatedError",
    "NotConnectedError",
    "Packet",
    "PacketKind",
    "PollWait",
    "PowerSource",
    "PowerState",
    "ProtocolError",
    "RangeError",
    "RawReply",
    "Registry",
    "Resource",
    "Setting",
    "SettingValue",
    "Settings",
    "Shooting",
    "ShootingError",
    "ShutterAction",
    "StateChange",
    "Status",
    "Storage",
    "StorageError",
    "Stream",
    "ThermalRestriction",
    "Transport",
    "UnacceptableVersionError",
    "UnreachableError",
    "Unpacker",
    "ViewSize",
    "Volatility",
    "ZoomAction",
    "error_for",
    "pack",
    "unpack",
    "volatility_of",
    "worth_retrying",
]
