"""One vocabulary three unrelated subsystems speak, so one screen renders declarations.

The subsystem declares what only it can know; everything else is the GUI's. A
declaration imports this package and this package imports nothing back.
"""

from shared.bench_api.inputs import (
    as_bytes,
    bitmask,
    blank_values,
    boolean,
    checked_inputs,
    choice,
    coerced_values,
    current_options,
    group,
    inputs_for,
    integer,
    labelled_options,
    overridden,
    raw_bytes,
)
from shared.bench_api.json_helpers import (
    input_json,
    options_of,
    outcome_json,
    readiness_json,
    result_json,
    routine_json,
)
from shared.bench_api.records import (
    CALL,
    FAILED,
    LINK,
    PASSED,
    PRELINK,
    READY,
    SETUP,
    SKIPPED,
    WARNED,
    Abandoned,
    Behaviour,
    Category,
    DeclarationError,
    Input,
    Level,
    LogEvent,
    Option,
    Readiness,
    Result,
    Routine,
    StepOutcome,
    StepStatus,
    SubsystemBench,
    Table,
    blocked,
)
from shared.bench_api.registry import (
    REGISTRY,
    Registry,
    derive,
    link_routine,
    readiness_of,
    readiness_with,
    register_routine,
    routine,
    run_routine,
)
from shared.bench_api.run_log import verdict
from shared.subsystem import SubsystemLinkState, SubsystemSpec, summary_and_body, titled

__all__ = [
    "CALL",
    "FAILED",
    "LINK",
    "PASSED",
    "PRELINK",
    "READY",
    "REGISTRY",
    "SETUP",
    "SKIPPED",
    "WARNED",
    "Abandoned",
    "Behaviour",
    "Category",
    "DeclarationError",
    "Input",
    "Level",
    "LogEvent",
    "Option",
    "Readiness",
    "Registry",
    "Result",
    "Routine",
    "StepOutcome",
    "StepStatus",
    "SubsystemBench",
    "SubsystemSpec",
    "SubsystemLinkState",
    "Table",
    "as_bytes",
    "bitmask",
    "blank_values",
    "blocked",
    "boolean",
    "checked_inputs",
    "choice",
    "coerced_values",
    "current_options",
    "derive",
    "group",
    "input_json",
    "inputs_for",
    "integer",
    "labelled_options",
    "link_routine",
    "options_of",
    "outcome_json",
    "overridden",
    "raw_bytes",
    "readiness_json",
    "result_json",
    "readiness_of",
    "readiness_with",
    "register_routine",
    "routine",
    "routine_json",
    "run_routine",
    "summary_and_body",
    "verdict",
    "titled",
]
